# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# pod 'PullToRefreshSwift'
# pod 'MMLocalization'
pod 'WeatherAPI', :path =>'../API/WeatherAPI.podspec'
pod 'SDWebImage'
pod 'Popover'

  # Pods for WeatherApp

end


