//
// WeatherResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class WeatherResponse: JSONEncodable {

    public var cod: String?
    public var cnt: Int32?
    public var list: [FullWeather]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["cod"] = self.cod
        nillableDictionary["cnt"] = self.cnt?.encodeToJSON()
        nillableDictionary["list"] = self.list?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
