//
// Wheather.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Wheather: JSONEncodable {

    public var id: Int32?
    public var main: String?
    public var description: String?
    public var icon: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["main"] = self.main
        nillableDictionary["description"] = self.description
        nillableDictionary["icon"] = self.icon

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
